# Copyright 2011 The snappy-go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=snappy-go.googlecode.com/hg/zigzag
GOFILES=\
	zigzag.go\

include $(GOROOT)/src/Make.pkg

